table Dim_Store

	column StoreId
		dataType: string
		sourceColumn: StoreId
		summarizeBy: none
		isKey

	column StoreName
		dataType: string
		sourceColumn: StoreName
		summarizeBy: none

	column Region
		dataType: string
		sourceColumn: Region
		summarizeBy: none

	column StoreFormat
		dataType: string
		sourceColumn: StoreFormat
		summarizeBy: none

	partition Dim_Store = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(SourceFilePath), null, true),
					Data = Source{[Item="Stores",Kind="Sheet"]}[Data],
					Promoted = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted,{
						{"StoreId", type text}, {"StoreName", type text},
						{"Region", type text}, {"StoreFormat", type text}
					})
				in
					Typed

	annotation PBI_ResultType = Table
