name: Deploy .NET API to Azure

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual branch selection in GitHub UI

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore StudioTechBI.Backend/StudioTechBI.Backend.API

    - name: Build
      run: dotnet build StudioTechBI.Backend/StudioTechBI.Backend.API --configuration Release --no-restore

    - name: Publish
      run: dotnet publish StudioTechBI.Backend/StudioTechBI.Backend.API -c Release -o publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: studiotechbi-api
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish
